version: "3"
services:
  discord-bot:
    restart: always
    build: .
    environment: 
      DISCORD_BOT_TOKEN: "yourtoken"
      SA_KEY_FILE: "sa-key.json"
      WORKSHEET_NAME: "Google スプレッドシート名"
      TITLE: "Google スプレッドシート名"
    volumes:
      - .:/app:rw
