version: "3"
services:
  discord-bot:
    restart: always
    build: .
    environment: 
      DISCORD_BOT_TOKEN: "yourtoken"
      WORKSHEET_NAME: "sa-key.json"
      TITLE: "参加メンバー"
    volumes:
      - .:/app:rw
